// GOD2 · Theophas Aine · interdits
//
// Cherche dans le dépôt ce que `regles/INTERDITS.md` proscrit, et sort en
// erreur si quelque chose remonte.
//
//   npm run interdits            tout le projet
//   npm run interdits src        un sous-dossier
//
// Le fichier de règles lui-même est exclu : il cite ce qu'il interdit.

import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative, sep } from 'node:path'

const RACINE = process.cwd()
const DEPART = process.argv[2] ?? '.'

// « references » garde les pieces d origine : photographies de Wikimedia
// Commons, et le dossier de sources de ThreeUI quand il est present en local.
// Ce sont les mots des autres, pas les notres, et le controle n a pas a les
// corriger. Ce qu on en tire, lui, est controle : tout src/paysage/ passe ici.
const DOSSIERS_IGNORES = new Set([
  'node_modules', 'dist', '.git', 'public', 'references', 'vues',
])
// Le contrôle cite les motifs qu'il cherche : il se trouverait lui-même.
const FICHIERS_IGNORES = new Set(['package-lock.json', 'interdits.mjs'])
const EXTENSIONS = new Set([
  '.tsx', '.ts', '.jsx', '.js', '.mjs', '.css', '.html', '.json', '.md',
  '.py', '.php', '.txt', '.yml', '.yaml',
])

// Les documents qui énoncent les règles citent forcément ce qu'ils proscrivent.
const DOCUMENTS_DE_REGLES = [/^(CLAUDE|SKILL)\.md$/, /^skills_MD\//]

/** Chaque règle dit ce qu'elle cherche et ce qu'il faut écrire à la place. */
const REGLES = [
  {
    nom: 'tiret cadratin',
    motif: /[—–]/,
    remede: 'virgule, deux-points, point médian ou tiret court selon le sens',
  },
  {
    nom: 'signature d\'outil',
    motif: /Co-Authored-By|Built with Claude|Generated by (AI|Claude)|Powered by AI|🤖/i,
    remede: 'rien : les dépôts sont remis à des tiers',
    saufDans: DOCUMENTS_DE_REGLES,
  },
  {
    nom: 'texte de remplissage',
    motif: /Lorem ipsum|John Doe|Jane (Doe|Smith)/i,
    remede: 'un nom béninois et du vrai copy',
    saufDans: DOCUMENTS_DE_REGLES,
  },
  {
    nom: 'nom de fantaisie générique',
    motif: /\b(Acme|Aurora|Nebula|Orion|Zenith|Vertex)\b/,
    remede: 'Gblewa, Dantokpa, Cadjèhoun, Ganvié, Ouidah…',
    saufDans: DOCUMENTS_DE_REGLES,
  },
  {
    nom: 'embed d\'un service externe',
    motif: /spline\.design|unicorn\.studio|framer\.com\/embed|my\.spline/i,
    remede: 'une reprise locale en CSS, SVG, canvas ou WebGL',
    saufDans: DOCUMENTS_DE_REGLES,
  },
  {
    nom: 'copy creux',
    motif: /Élevez votre|Libérez la puissance|Bienvenue sur notre site|Découvrez nos services|en toute simplicité/i,
    remede: 'une phrase qui dit ce que la chose fait, pour qui',
    saufDans: DOCUMENTS_DE_REGLES,
  },
]

/**
 * Le code cité dans un document ne compte pas.
 *
 * Un journal de leçons doit pouvoir montrer le caractère qu'il proscrit. Cela
 * ne vaut que pour le markdown : dans un `.ts`, ce qui est entre accents graves
 * est un gabarit de chaîne, donc du texte affiché.
 */
function sansCodeCite(ligne) {
  return ligne.replace(/`[^`]*`/g, '``')
}

function* fichiers(depart) {
  for (const entree of readdirSync(depart)) {
    const chemin = join(depart, entree)
    let etat
    try {
      etat = statSync(chemin)
    } catch {
      continue
    }
    if (etat.isDirectory()) {
      if (DOSSIERS_IGNORES.has(entree)) continue
      yield* fichiers(chemin)
      continue
    }
    if (FICHIERS_IGNORES.has(entree)) continue
    const point = entree.lastIndexOf('.')
    if (point < 0 || !EXTENSIONS.has(entree.slice(point))) continue
    yield chemin
  }
}

const trouves = []

for (const chemin of fichiers(DEPART)) {
  let lignes
  try {
    lignes = readFileSync(chemin, 'utf8').split('\n')
  } catch {
    continue
  }
  for (let rang = 0; rang < lignes.length; rang += 1) {
    for (const regle of REGLES) {
      const relatif = relative(RACINE, chemin).split(sep).join('/')
      if (regle.saufDans?.some((exception) => exception.test(relatif))) continue
      const lue = chemin.endsWith('.md') ? sansCodeCite(lignes[rang]) : lignes[rang]
      if (regle.motif.test(lue)) {
        trouves.push({
          fichier: relatif,
          ligne: rang + 1,
          regle,
          texte: lignes[rang].trim().slice(0, 100),
        })
      }
    }
  }
}

if (trouves.length === 0) {
  console.log('Aucun interdit trouvé.')
  process.exit(0)
}

const parRegle = new Map()
for (const trouve of trouves) {
  if (!parRegle.has(trouve.regle.nom)) parRegle.set(trouve.regle.nom, [])
  parRegle.get(trouve.regle.nom).push(trouve)
}

for (const [nom, liste] of parRegle) {
  console.log(`\n${nom} : ${liste.length}`)
  console.log(`  à la place : ${liste[0].regle.remede}`)
  for (const trouve of liste.slice(0, 12)) {
    console.log(`  ${trouve.fichier}:${trouve.ligne}`)
    console.log(`      ${trouve.texte}`)
  }
  if (liste.length > 12) console.log(`  … et ${liste.length - 12} autres`)
}

console.log(`\n${trouves.length} interdits. Voir regles/INTERDITS.md.`)
process.exit(1)
